//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerrithewDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public int id { get; set; }
        public string type_code { get; set; }
        public string type_desc { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string notes { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
    }
}
